<?php 
/**
 * Aydus_AdminOrderAnalytics order template
 *
 * @category   Aydus
 * @package    Aydus_AdminOrderAnalytics
 * @author     Aydus <davidt@aydus.com>
 */

if ($this->isEnabled()):

$account = $this->getAccount();
$order = $this->getCurrentOrder();
$items = $this->getItems();
?>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '<?php echo $account ?>', 'auto');
  ga('send', 'pageview');
  
  ga('require', 'ecommerce', 'ecommerce.js');
  ga('ecommerce:addTransaction', { 'id': '<?php echo $order->getIncrementId() ?>', 'affiliation': '<?php echo $order->getStore()->getName() ?>', 'revenue': '<?php echo $order->getGrandTotal() ?>', 'shipping': '<?php $order->getShippingInclTax() ?>', 'tax': '<?php echo  $order->getTaxAmount()?>', 'currency': '<?php echo $order->getOrderCurrencyCode();?>'});
  <?php foreach ($items as $item): ?>
  ga('ecommerce:addItem', {'id': '<?php echo $order->getIncrementId() ?>', 'name': '<?php echo $item->getName() ?>', 'sku': '<?php echo $item->getSku() ?>', 'price': '<?php echo $item->getPrice() ?>', 'quantity': '<?php echo $item->getQtyOrdered() ?>'});
  <?php endforeach; ?>

  ga('ecommerce:send');
</script>
<?php 
endif;
?>